# Site settings

title: Guillermo Zafra - iOS Engineer # iOS Engineer
email: me@gzafra.com # Your contant email

description: Website and Portfolio of Guillermo Zafra, iOS Engineer. Native Apps and Games Developer with experience with Objective C, Swift, C# and Agile projects.
baseurl: "/web" # the subpath of your site, e.g. /blog/
url: "https://nilart.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     nilart  # Replace this with your Twitter username
github_username:      nilart  # Replace this with your GitHub username
linkedin_username:    gzafra  # Replace this with your LinkedIn username
facebook_username:      # Replace this with your Facebook username
skype_username:      # Replace this with your Dribbble username
stackoverflow_username: 992934/gzafra

# Build settings
markdown: kramdown
